### ISSUE TITLE
Hello, Same problem to me. Have you solved?

### ISSUE THREAD

**Issue by guohan950106** [abdulfatir/prototypical-networks-tensorflow#6] opened 2018-09-26 08:16 UTC
I ran Proto-MiniImagenet and I got followings 
[epoch 93/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 94/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 94/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 95/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 95/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 96/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 96/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 97/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 97/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 98/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 98/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 99/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 99/100, episode 100/100] => loss: 2.99573, acc: 0.05000
[epoch 100/100, episode 50/100] => loss: 2.99573, acc: 0.05000
[epoch 100/100, episode 100/100] => loss: 2.99573, acc: 0.05000

same accuracy for every episode. 
And weird thing is that this wasn't happening for Proto-Omniglot. 
My tensorflow is for GPU and version 1.3

_Originally posted by @themis0888 in https://github.com/abdulfatir/prototypical-networks-tensorflow/issues/1#issuecomment-383084528_

**Comment by abdulfatir** [comment] 2018-09-26 09:20
Did you check with a different version of TF (I used tf 1.4 AFAIR)? Did you try running multiple times?

**Comment by guohan950106** [comment] 2018-09-26 10:01
Thanks for you reply! Ihave tried TF 1.8.0 and 1.10.0. but the same result.

Abdul Fatir <notifications@github.com> 于2018年9月26日周三 下午5:20写道：

**Comment by abdulfatir** [comment] 2018-09-26 15:31
I didn't face such an issue when I last updated this repo as you can see from the output in the notebook. I'll try to look into it in a few days.

**Comment by abdulfatir** [comment] 2018-09-26 15:34
Duplicate of #1

**Closed as completed by abdulfatir** 2018-09-26 15:34 UTC
